---
- name: Deploy Parasol Insurance Website to RHEL 9 with Nginx
  hosts: all
  become: true
  gather_facts: false
  vars:
    website_url: "https://github.com/ansible-tmm/parasol-website"
    nginx_root: "/usr/share/nginx/html"

  tasks:
    - name: Run Nginx installation tasks
      ansible.builtin.import_tasks: tasks/install_nginx-rhel.yml
